export default function Surah() {
  const sorah = {
    60: [
      {
        number: 87,
        name: 'الأعلى',
        englishName: "Al-A'la",
        numberOfAyahs: 19,
        index: 0,
      },
      {
        number: 88,
        name: 'الغاشية',
        englishName: 'Al-Ghashiyah',
        numberOfAyahs: 26,
        index: 1,
      },
      {
        number: 89,
        name: 'الفجر',
        englishName: 'Al-Fajr',
        numberOfAyahs: 30,
        index: 2,
      },
      {
        number: 90,
        name: 'البلد',
        englishName: 'Al-Balad',
        numberOfAyahs: 20,
        index: 3,
      },
      {
        number: 91,
        name: 'الشمس',
        englishName: 'Ash-Shams',
        numberOfAyahs: 15,
        index: 4,
      },
      {
        number: 92,
        name: 'الليل',
        englishName: 'Al-Layl',
        numberOfAyahs: 21,
        index: 5,
      },
      {
        number: 93,
        name: 'الضحى',
        englishName: 'Ad-Duha',
        numberOfAyahs: 11,
        index: 6,
      },
      {
        number: 94,
        name: 'الشرح',
        englishName: 'Ash-Sharh',
        numberOfAyahs: 8,
        index: 7,
      },
      {
        number: 95,
        name: 'التين',
        englishName: 'At-Tin',
        numberOfAyahs: 8,
        index: 8,
      },
      {
        number: 96,
        name: 'العلق',
        englishName: 'Al-Alaq',
        numberOfAyahs: 19,
        index: 9,
      },
      {
        number: 97,
        name: 'القدر',
        englishName: 'Al-Qadr',
        numberOfAyahs: 5,
        index: 10,
      },
      {
        number: 98,
        name: 'البينة',
        englishName: 'Al-Bayyina',
        numberOfAyahs: 8,
        index: 11,
      },
      {
        number: 99,
        name: 'الزلزلة',
        englishName: 'Az-Zalzalah',
        numberOfAyahs: 8,
        index: 12,
      },
      {
        number: 100,
        name: 'العاديات',
        englishName: 'Al-Adiyat',
        numberOfAyahs: 11,
        index: 13,
      },
      {
        number: 101,
        name: 'القارعة',
        englishName: "Al-Qari'ah",
        numberOfAyahs: 11,
        index: 14,
      },
      {
        number: 102,
        name: 'التكاثر',
        englishName: 'At-Takathur',
        numberOfAyahs: 8,
        index: 15,
      },
      {
        number: 103,
        name: 'العصر',
        englishName: 'Al-Asr',
        numberOfAyahs: 3,
        index: 16,
      },
      {
        number: 104,
        name: 'الهمزة',
        englishName: 'Al-Humazah',
        numberOfAyahs: 9,
        index: 17,
      },
      {
        number: 105,
        name: 'الفيل',
        englishName: 'Al-Fil',
        numberOfAyahs: 5,
        index: 18,
      },
      {
        number: 106,
        name: 'قريش',
        englishName: 'Quraysh',
        numberOfAyahs: 4,
        index: 19,
      },
      {
        number: 107,
        name: 'الماعون',
        englishName: "Al-Ma'un",
        numberOfAyahs: 7,
        index: 20,
      },
      {
        number: 108,
        name: 'الكوثر',
        englishName: 'Al-Kawthar',
        numberOfAyahs: 3,
        index: 21,
      },
      {
        number: 109,
        name: 'الكافرون',
        englishName: 'Al-Kafirun',
        numberOfAyahs: 6,
        index: 22,
      },
      {
        number: 110,
        name: 'النصر',
        englishName: 'An-Nasr',
        numberOfAyahs: 3,
        index: 23,
      },
      {
        number: 111,
        name: 'المسد',
        englishName: 'Al-Masad',
        numberOfAyahs: 5,
        index: 24,
      },
      {
        number: 112,
        name: 'الإخلاص',
        englishName: 'Al-Ikhlas',
        numberOfAyahs: 4,
        index: 25,
      },
      {
        number: 113,
        name: 'الفلق',
        englishName: 'Al-Falaq',
        numberOfAyahs: 5,
        index: 26,
      },
      {
        number: 114,
        name: 'الناس',
        englishName: 'An-Nas',
        numberOfAyahs: 6,
        index: 27,
      },
    ],

    59: [
      {
        number: 78,
        name: 'النبأ',
        englishName: 'An-Naba',
        numberOfAyahs: 40,
        index: 0,
      },
      {
        number: 79,
        name: 'النازعات',
        englishName: "An-Nazi'at",
        numberOfAyahs: 46,
        index: 1,
      },
      {
        number: 80,
        name: 'عبس',
        englishName: 'Abasa',
        numberOfAyahs: 42,
        index: 2,
      },
      {
        number: 81,
        name: 'التكوير',
        englishName: 'At-Takwir',
        numberOfAyahs: 29,
        index: 3,
      },
      {
        number: 82,
        name: 'الإنفطار',
        englishName: 'Al-Infitar',
        numberOfAyahs: 19,
        index: 4,
      },
      {
        number: 83,
        name: 'المطففين',
        englishName: 'Al-Mutaffifin',
        numberOfAyahs: 36,
        index: 5,
      },
      {
        number: 84,
        name: 'الإنشقاق',
        englishName: 'Al-Inshiqaq',
        numberOfAyahs: 25,
        index: 6,
      },
      {
        number: 85,
        name: 'البروج',
        englishName: 'Al-Buruj',
        numberOfAyahs: 22,
        index: 7,
      },
      {
        number: 86,
        name: 'الطارق',
        englishName: 'At-Tariq',
        numberOfAyahs: 17,
        index: 8,
      },
    ],

    58: [
      {
        number: 72,
        name: 'الجن',
        englishName: 'Al-Jinn',
        numberOfAyahs: 28,
        index: 0,
      },
      {
        number: 73,
        name: 'المزمل',
        englishName: 'Al-Muzzammil',
        numberOfAyahs: 20,
        index: 1,
      },
      {
        number: 74,
        name: 'المدثر',
        englishName: 'Al-Muddathir',
        numberOfAyahs: 56,
        index: 2,
      },
      {
        number: 75,
        name: 'القيامة',
        englishName: 'Al-Qiyamah',
        numberOfAyahs: 40,
        index: 3,
      },
      {
        number: 76,
        name: 'الإنسان',
        englishName: 'Al-Insan',
        numberOfAyahs: 31,
        index: 4,
      },
      {
        number: 77,
        name: 'المرسلات',
        englishName: 'Al-Mursalat',
        numberOfAyahs: 50,
        index: 5,
      },
    ],

    57: [
      {
        number: 67,
        name: 'الملك',
        englishName: 'Al-Mulk',
        numberOfAyahs: 30,
        index: 0,
      },
      {
        number: 68,
        name: 'القلم',
        englishName: 'Al-Qalam',
        numberOfAyahs: 52,
        index: 1,
      },
      {
        number: 69,
        name: 'الحاقة',
        englishName: 'Al-Haqqah',
        numberOfAyahs: 52,
        index: 2,
      },
      {
        number: 70,
        name: 'المعارج',
        englishName: "Al-Ma'arij",
        numberOfAyahs: 44,
        index: 3,
      },
      {
        number: 71,
        name: 'نوح',
        englishName: 'Nuh',
        numberOfAyahs: 28,
        index: 4,
      },
    ],

    56: [
      {
        number: 62,
        name: 'الجمعة',
        englishName: "Al-Jumu'ah",
        numberOfAyahs: 11,
        index: 0,
      },
      {
        number: 63,
        name: 'المنافقون',
        englishName: 'Al-Munafiqun',
        numberOfAyahs: 11,
        index: 1,
      },
      {
        number: 64,
        name: 'التغابن',
        englishName: 'At-Taghabun',
        numberOfAyahs: 18,
        index: 2,
      },
      {
        number: 65,
        name: 'الطلاق',
        englishName: 'At-Talaq',
        numberOfAyahs: 12,
        index: 3,
      },
      {
        number: 66,
        name: 'التحريم',
        englishName: 'At-Tahrim',
        numberOfAyahs: 12,
        index: 4,
      },
    ],

    55: [
      {
        number: 58,
        name: 'المجادلة',
        englishName: 'Al-Mujadila',
        numberOfAyahs: 22,
        index: 0,
      },
      {
        number: 59,
        name: 'الحشر',
        englishName: 'Al-Hashr',
        numberOfAyahs: 24,
        index: 1,
      },
      {
        number: 60,
        name: 'الممتحنة',
        englishName: 'Al-Mumtahanah',
        numberOfAyahs: 13,
        index: 2,
      },
      {
        number: 61,
        name: 'الصف',
        englishName: 'As-Saff',
        numberOfAyahs: 14,
        index: 3,
      },
    ],

    54: [
      {
        number: 55,
        name: 'الرحمن',
        englishName: 'Ar-Rahman',
        numberOfAyahs: 78,
        index: 0,
      },
      {
        number: 56,
        name: 'الواقعة',
        englishName: "Al-Waqi'ah",
        numberOfAyahs: 96,
        index: 1,
      },
      {
        number: 57,
        name: 'الحديد',
        englishName: 'Al-Hadid',
        numberOfAyahs: 29,
        index: 2,
      },
    ],
  };

  return sorah;
}
